name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.1"
          rebar3-version: "3"
          # elixir-version: "1"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      
      - name: Install dependencies
        run: gleam deps download
      
      - name: Build Erlang
        run: gleam build --target erl
      
      
      - name: Build JavaScript
        run: gleam build --target js
      
      - name: Test formatting
        run: gleam format --check src test
      
      - name: Test Erlang
        run: gleam test --target erl
      
      - name: Test JavaScript
        run: gleam test --target js
